# Quint configuration for JAM Protocol specification

[project]
name = "confiture"
version = "0.1.5"
description = "JAM Protocol formal specification in Quint"

[verification]
# Default verification settings
max-steps = 100
init = "init"
step = "step"
invariant = ["system_invariant"]

[simulation]
# Simulation settings for random testing
seed = 12345
max-runs = 10
max-steps = 50

[apalache]
# Settings for Apalache model checker
length = 20
init = "init"
next = "step"
inv = ["system_invariant"]

[[test]]
name = "testsuite53"
file = "tests/test_validator_assignment_3cores.qnt"
runs = [
  "test_validator_assignment_3cores"
]